Story/ccls-1998_2013_15 opponents endpoints
ministryofjustice/laa-ccms-caab-api pull request #25
Opened 2024-01-25 14:23 UTC by porritta

Includes
CCLS-1998
CCLS-2013
CCLS-2014
CCLS-2015

2024-01-25 16:02 UTC, PhilDigitalJustice commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Opponent.java
> +  private Boolean appMode = true;
Should we not be setting these?

2024-01-25 16:02 UTC, PhilDigitalJustice commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Opponent.java
> +  private Boolean amendment = false;
Should we not be setting these?

2024-01-25 16:02 UTC, PhilDigitalJustice commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Opponent.java
> +  private Boolean award = false;
Should we not be setting these?

2024-01-25 16:02 UTC, PhilDigitalJustice commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Opponent.java
> +  private Boolean sharedInd = false;
Should we not be setting these?

2024-01-25 16:02 UTC, PhilDigitalJustice commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Opponent.java
> +  private Boolean deleteInd = true;
Should we not be setting these?

2024-01-25 16:03 UTC, PhilDigitalJustice commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Proceeding.java
> +  private Boolean leadProceedingInd = false;
Should we not be setting these?

2024-01-25 16:05 UTC, PhilDigitalJustice requested changes
A few comments around the same issue, rest looks good

2024-01-25 17:11 UTC, porritta commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Opponent.java
> +  private Boolean appMode = true;
Amended

2024-01-25 17:12 UTC, porritta commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Opponent.java
> +  private Boolean award = false;
Amended

2024-01-25 17:12 UTC, porritta commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Opponent.java
> +  private Boolean deleteInd = true;
Amended

2024-01-25 17:12 UTC, porritta commented on caab-service/src/main/java/uk/gov/laa/ccms/caab/api/entity/Proceeding.java
> +  private Boolean leadProceedingInd = false;
Amended

2024-01-26 09:51 UTC, PhilDigitalJustice approved these changes

2024-01-26 09:51 UTC, PhilDigitalJustice commented
LGTM

2024-01-26 09:52 UTC, merged